version: "3"

services:
  myapp2:
    build:
      context: .
      dockerfile: aneeshseth/api-mine:${{ github.sha }}
    ports:
      - "3004:3004"
    volumes:
      - myapp:/home/node/app

volumes:
  myapp:
